[2023-11-06T12:05:54.450+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-14T00:00:00+00:00 [queued]>
[2023-11-06T12:05:54.490+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-14T00:00:00+00:00 [queued]>
[2023-11-06T12:05:54.493+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-11-06T12:05:54.559+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): task_a> on 2023-10-14 00:00:00+00:00
[2023-11-06T12:05:54.580+0000] {standard_task_runner.py:57} INFO - Started process 819 to run task
[2023-11-06T12:05:54.611+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'catchup_and_backfill_dag', 'task_a', 'scheduled__2023-10-14T00:00:00+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/catchup_and_backfill_dag.py', '--cfg-path', '/tmp/tmppa76dp9h']
[2023-11-06T12:05:54.623+0000] {standard_task_runner.py:85} INFO - Job 86: Subtask task_a
[2023-11-06T12:05:54.817+0000] {task_command.py:416} INFO - Running <TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-14T00:00:00+00:00 [running]> on host cf1baac588aa
[2023-11-06T12:05:55.082+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='safarnejad' AIRFLOW_CTX_DAG_ID='catchup_and_backfill_dag' AIRFLOW_CTX_TASK_ID='task_a' AIRFLOW_CTX_EXECUTION_DATE='2023-10-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-14T00:00:00+00:00'
[2023-11-06T12:05:55.087+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-06T12:05:55.089+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo Hello World :)']
[2023-11-06T12:05:55.122+0000] {subprocess.py:86} INFO - Output:
[2023-11-06T12:05:55.131+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: syntax error near unexpected token `)'
[2023-11-06T12:05:55.136+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: `echo Hello World :)'
[2023-11-06T12:05:55.137+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-11-06T12:05:55.173+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-11-06T12:05:55.199+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=catchup_and_backfill_dag, task_id=task_a, execution_date=20231014T000000, start_date=20231106T120554, end_date=20231106T120555
[2023-11-06T12:05:55.241+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 86 for task task_a (Bash command failed. The command returned a non-zero exit code 2.; 819)
[2023-11-06T12:05:55.310+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-06T12:05:55.412+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
