[2023-11-06T12:03:52.274+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-15T00:00:00+00:00 [queued]>
[2023-11-06T12:03:52.293+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-15T00:00:00+00:00 [queued]>
[2023-11-06T12:03:52.295+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-06T12:03:52.460+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): task_a> on 2023-10-15 00:00:00+00:00
[2023-11-06T12:03:52.467+0000] {standard_task_runner.py:57} INFO - Started process 671 to run task
[2023-11-06T12:03:52.472+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'catchup_and_backfill_dag', 'task_a', 'scheduled__2023-10-15T00:00:00+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/catchup_and_backfill_dag.py', '--cfg-path', '/tmp/tmpaddmgrm5']
[2023-11-06T12:03:52.477+0000] {standard_task_runner.py:85} INFO - Job 73: Subtask task_a
[2023-11-06T12:03:52.559+0000] {task_command.py:416} INFO - Running <TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-15T00:00:00+00:00 [running]> on host cf1baac588aa
[2023-11-06T12:03:52.673+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='safarnejad' AIRFLOW_CTX_DAG_ID='catchup_and_backfill_dag' AIRFLOW_CTX_TASK_ID='task_a' AIRFLOW_CTX_EXECUTION_DATE='2023-10-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-15T00:00:00+00:00'
[2023-11-06T12:03:52.675+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-06T12:03:52.676+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo Hello World :)']
[2023-11-06T12:03:52.687+0000] {subprocess.py:86} INFO - Output:
[2023-11-06T12:03:52.689+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: syntax error near unexpected token `)'
[2023-11-06T12:03:52.690+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: `echo Hello World :)'
[2023-11-06T12:03:52.691+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-11-06T12:03:52.705+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-11-06T12:03:52.711+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=catchup_and_backfill_dag, task_id=task_a, execution_date=20231015T000000, start_date=20231106T120352, end_date=20231106T120352
[2023-11-06T12:03:52.728+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 73 for task task_a (Bash command failed. The command returned a non-zero exit code 2.; 671)
[2023-11-06T12:03:52.767+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-06T12:03:52.804+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-06T12:17:59.550+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-15T00:00:00+00:00 [queued]>
[2023-11-06T12:17:59.573+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-15T00:00:00+00:00 [queued]>
[2023-11-06T12:17:59.574+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-06T12:17:59.745+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): task_a> on 2023-10-15 00:00:00+00:00
[2023-11-06T12:17:59.753+0000] {standard_task_runner.py:57} INFO - Started process 1920 to run task
[2023-11-06T12:17:59.761+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'catchup_and_backfill_dag', 'task_a', 'scheduled__2023-10-15T00:00:00+00:00', '--job-id', '145', '--raw', '--subdir', 'DAGS_FOLDER/catchup_and_backfill_dag.py', '--cfg-path', '/tmp/tmpxd4k9o4v']
[2023-11-06T12:17:59.768+0000] {standard_task_runner.py:85} INFO - Job 145: Subtask task_a
[2023-11-06T12:17:59.878+0000] {task_command.py:416} INFO - Running <TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-15T00:00:00+00:00 [running]> on host cf1baac588aa
[2023-11-06T12:18:00.083+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='safarnejad' AIRFLOW_CTX_DAG_ID='catchup_and_backfill_dag' AIRFLOW_CTX_TASK_ID='task_a' AIRFLOW_CTX_EXECUTION_DATE='2023-10-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-15T00:00:00+00:00'
[2023-11-06T12:18:00.089+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-06T12:18:00.090+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo Hello World :)']
[2023-11-06T12:18:00.117+0000] {subprocess.py:86} INFO - Output:
[2023-11-06T12:18:00.121+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: syntax error near unexpected token `)'
[2023-11-06T12:18:00.122+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: `echo Hello World :)'
[2023-11-06T12:18:00.124+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-11-06T12:18:00.157+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-11-06T12:18:00.163+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=catchup_and_backfill_dag, task_id=task_a, execution_date=20231015T000000, start_date=20231106T121759, end_date=20231106T121800
[2023-11-06T12:18:00.189+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 145 for task task_a (Bash command failed. The command returned a non-zero exit code 2.; 1920)
[2023-11-06T12:18:00.220+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-06T12:18:00.251+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-06T12:19:05.910+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-15T00:00:00+00:00 [queued]>
[2023-11-06T12:19:05.935+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-15T00:00:00+00:00 [queued]>
[2023-11-06T12:19:05.936+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-06T12:19:05.982+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): task_a> on 2023-10-15 00:00:00+00:00
[2023-11-06T12:19:05.995+0000] {standard_task_runner.py:57} INFO - Started process 2037 to run task
[2023-11-06T12:19:06.014+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'catchup_and_backfill_dag', 'task_a', 'scheduled__2023-10-15T00:00:00+00:00', '--job-id', '161', '--raw', '--subdir', 'DAGS_FOLDER/catchup_and_backfill_dag.py', '--cfg-path', '/tmp/tmp99ltt4gr']
[2023-11-06T12:19:06.019+0000] {standard_task_runner.py:85} INFO - Job 161: Subtask task_a
[2023-11-06T12:19:06.149+0000] {task_command.py:416} INFO - Running <TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-15T00:00:00+00:00 [running]> on host cf1baac588aa
[2023-11-06T12:19:06.349+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='safarnejad' AIRFLOW_CTX_DAG_ID='catchup_and_backfill_dag' AIRFLOW_CTX_TASK_ID='task_a' AIRFLOW_CTX_EXECUTION_DATE='2023-10-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-15T00:00:00+00:00'
[2023-11-06T12:19:06.352+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-06T12:19:06.355+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo Hello World.']
[2023-11-06T12:19:06.372+0000] {subprocess.py:86} INFO - Output:
[2023-11-06T12:19:06.378+0000] {subprocess.py:93} INFO - Hello World.
[2023-11-06T12:19:06.379+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-11-06T12:19:06.440+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=catchup_and_backfill_dag, task_id=task_a, execution_date=20231015T000000, start_date=20231106T121905, end_date=20231106T121906
[2023-11-06T12:19:06.516+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-06T12:19:06.660+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
