[2023-11-05T11:11:10.010+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.task_b manual__2023-11-05T11:11:06.643892+00:00 [queued]>
[2023-11-05T11:11:10.030+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.task_b manual__2023-11-05T11:11:06.643892+00:00 [queued]>
[2023-11-05T11:11:10.031+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-05T11:11:10.059+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): task_b> on 2023-11-05 11:11:06.643892+00:00
[2023-11-05T11:11:10.066+0000] {standard_task_runner.py:57} INFO - Started process 2313 to run task
[2023-11-05T11:11:10.071+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'task_b', 'manual__2023-11-05T11:11:06.643892+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpjxuq2m98']
[2023-11-05T11:11:10.080+0000] {standard_task_runner.py:85} INFO - Job 18: Subtask task_b
[2023-11-05T11:11:10.163+0000] {task_command.py:416} INFO - Running <TaskInstance: my_first_dag.task_b manual__2023-11-05T11:11:06.643892+00:00 [running]> on host 6f8d85da5f7c
[2023-11-05T11:11:10.294+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='safarnejad' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='task_b' AIRFLOW_CTX_EXECUTION_DATE='2023-11-05T11:11:06.643892+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-05T11:11:06.643892+00:00'
[2023-11-05T11:11:10.296+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-05T11:11:10.297+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cp consolidate_data.jpg consolidate.jpg']
[2023-11-05T11:11:10.308+0000] {subprocess.py:86} INFO - Output:
[2023-11-05T11:11:10.320+0000] {subprocess.py:93} INFO - cp: cannot stat 'consolidate_data.jpg': No such file or directory
[2023-11-05T11:11:10.321+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-11-05T11:11:10.337+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-11-05T11:11:10.351+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=my_first_dag, task_id=task_b, execution_date=20231105T111106, start_date=20231105T111110, end_date=20231105T111110
[2023-11-05T11:11:10.372+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 18 for task task_b (Bash command failed. The command returned a non-zero exit code 1.; 2313)
[2023-11-05T11:11:10.406+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-05T11:11:10.474+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
