[2023-11-06T12:03:52.522+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-16T00:00:00+00:00 [queued]>
[2023-11-06T12:03:52.537+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-16T00:00:00+00:00 [queued]>
[2023-11-06T12:03:52.538+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-06T12:03:52.561+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): task_a> on 2023-10-16 00:00:00+00:00
[2023-11-06T12:03:52.566+0000] {standard_task_runner.py:57} INFO - Started process 672 to run task
[2023-11-06T12:03:52.571+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'catchup_and_backfill_dag', 'task_a', 'scheduled__2023-10-16T00:00:00+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/catchup_and_backfill_dag.py', '--cfg-path', '/tmp/tmpm34_gjc4']
[2023-11-06T12:03:52.575+0000] {standard_task_runner.py:85} INFO - Job 74: Subtask task_a
[2023-11-06T12:03:52.648+0000] {task_command.py:416} INFO - Running <TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-16T00:00:00+00:00 [running]> on host cf1baac588aa
[2023-11-06T12:03:52.756+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='safarnejad' AIRFLOW_CTX_DAG_ID='catchup_and_backfill_dag' AIRFLOW_CTX_TASK_ID='task_a' AIRFLOW_CTX_EXECUTION_DATE='2023-10-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-16T00:00:00+00:00'
[2023-11-06T12:03:52.758+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-06T12:03:52.759+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo Hello World :)']
[2023-11-06T12:03:52.769+0000] {subprocess.py:86} INFO - Output:
[2023-11-06T12:03:52.772+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: syntax error near unexpected token `)'
[2023-11-06T12:03:52.773+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: `echo Hello World :)'
[2023-11-06T12:03:52.774+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-11-06T12:03:52.792+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-11-06T12:03:52.799+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=catchup_and_backfill_dag, task_id=task_a, execution_date=20231016T000000, start_date=20231106T120352, end_date=20231106T120352
[2023-11-06T12:03:52.824+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 74 for task task_a (Bash command failed. The command returned a non-zero exit code 2.; 672)
[2023-11-06T12:03:52.866+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-06T12:03:52.898+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-06T12:17:59.857+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-16T00:00:00+00:00 [queued]>
[2023-11-06T12:17:59.879+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-16T00:00:00+00:00 [queued]>
[2023-11-06T12:17:59.880+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-06T12:17:59.911+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): task_a> on 2023-10-16 00:00:00+00:00
[2023-11-06T12:17:59.919+0000] {standard_task_runner.py:57} INFO - Started process 1922 to run task
[2023-11-06T12:17:59.927+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'catchup_and_backfill_dag', 'task_a', 'scheduled__2023-10-16T00:00:00+00:00', '--job-id', '146', '--raw', '--subdir', 'DAGS_FOLDER/catchup_and_backfill_dag.py', '--cfg-path', '/tmp/tmpquwdqpli']
[2023-11-06T12:17:59.933+0000] {standard_task_runner.py:85} INFO - Job 146: Subtask task_a
[2023-11-06T12:18:00.083+0000] {task_command.py:416} INFO - Running <TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-16T00:00:00+00:00 [running]> on host cf1baac588aa
[2023-11-06T12:18:00.266+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='safarnejad' AIRFLOW_CTX_DAG_ID='catchup_and_backfill_dag' AIRFLOW_CTX_TASK_ID='task_a' AIRFLOW_CTX_EXECUTION_DATE='2023-10-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-16T00:00:00+00:00'
[2023-11-06T12:18:00.268+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-06T12:18:00.270+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo Hello World :)']
[2023-11-06T12:18:00.289+0000] {subprocess.py:86} INFO - Output:
[2023-11-06T12:18:00.293+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: syntax error near unexpected token `)'
[2023-11-06T12:18:00.294+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: `echo Hello World :)'
[2023-11-06T12:18:00.295+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-11-06T12:18:00.312+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-11-06T12:18:00.320+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=catchup_and_backfill_dag, task_id=task_a, execution_date=20231016T000000, start_date=20231106T121759, end_date=20231106T121800
[2023-11-06T12:18:00.342+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 146 for task task_a (Bash command failed. The command returned a non-zero exit code 2.; 1922)
[2023-11-06T12:18:00.385+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-06T12:18:00.414+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-06T12:19:06.081+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-16T00:00:00+00:00 [queued]>
[2023-11-06T12:19:06.102+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-16T00:00:00+00:00 [queued]>
[2023-11-06T12:19:06.104+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-06T12:19:06.139+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): task_a> on 2023-10-16 00:00:00+00:00
[2023-11-06T12:19:06.147+0000] {standard_task_runner.py:57} INFO - Started process 2039 to run task
[2023-11-06T12:19:06.154+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'catchup_and_backfill_dag', 'task_a', 'scheduled__2023-10-16T00:00:00+00:00', '--job-id', '162', '--raw', '--subdir', 'DAGS_FOLDER/catchup_and_backfill_dag.py', '--cfg-path', '/tmp/tmpao2ylovf']
[2023-11-06T12:19:06.160+0000] {standard_task_runner.py:85} INFO - Job 162: Subtask task_a
[2023-11-06T12:19:06.267+0000] {task_command.py:416} INFO - Running <TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-16T00:00:00+00:00 [running]> on host cf1baac588aa
[2023-11-06T12:19:06.469+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='safarnejad' AIRFLOW_CTX_DAG_ID='catchup_and_backfill_dag' AIRFLOW_CTX_TASK_ID='task_a' AIRFLOW_CTX_EXECUTION_DATE='2023-10-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-16T00:00:00+00:00'
[2023-11-06T12:19:06.476+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-06T12:19:06.477+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo Hello World.']
[2023-11-06T12:19:06.500+0000] {subprocess.py:86} INFO - Output:
[2023-11-06T12:19:06.506+0000] {subprocess.py:93} INFO - Hello World.
[2023-11-06T12:19:06.508+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-11-06T12:19:06.567+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=catchup_and_backfill_dag, task_id=task_a, execution_date=20231016T000000, start_date=20231106T121906, end_date=20231106T121906
[2023-11-06T12:19:06.698+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-06T12:19:06.758+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
