[2023-11-06T12:03:49.409+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-01T00:00:00+00:00 [queued]>
[2023-11-06T12:03:49.439+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-01T00:00:00+00:00 [queued]>
[2023-11-06T12:03:49.440+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-06T12:03:49.514+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): task_a> on 2023-10-01 00:00:00+00:00
[2023-11-06T12:03:49.525+0000] {standard_task_runner.py:57} INFO - Started process 630 to run task
[2023-11-06T12:03:49.537+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'catchup_and_backfill_dag', 'task_a', 'scheduled__2023-10-01T00:00:00+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/catchup_and_backfill_dag.py', '--cfg-path', '/tmp/tmpr4bt8331']
[2023-11-06T12:03:49.543+0000] {standard_task_runner.py:85} INFO - Job 60: Subtask task_a
[2023-11-06T12:03:49.702+0000] {task_command.py:416} INFO - Running <TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-01T00:00:00+00:00 [running]> on host cf1baac588aa
[2023-11-06T12:03:49.974+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='safarnejad' AIRFLOW_CTX_DAG_ID='catchup_and_backfill_dag' AIRFLOW_CTX_TASK_ID='task_a' AIRFLOW_CTX_EXECUTION_DATE='2023-10-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-01T00:00:00+00:00'
[2023-11-06T12:03:49.982+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-06T12:03:49.985+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo Hello World :)']
[2023-11-06T12:03:50.003+0000] {subprocess.py:86} INFO - Output:
[2023-11-06T12:03:50.010+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: syntax error near unexpected token `)'
[2023-11-06T12:03:50.012+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: `echo Hello World :)'
[2023-11-06T12:03:50.013+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-11-06T12:03:50.041+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-11-06T12:03:50.060+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=catchup_and_backfill_dag, task_id=task_a, execution_date=20231001T000000, start_date=20231106T120349, end_date=20231106T120350
[2023-11-06T12:03:50.107+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 60 for task task_a (Bash command failed. The command returned a non-zero exit code 2.; 630)
[2023-11-06T12:03:50.127+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-06T12:03:50.175+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-06T12:17:55.176+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-01T00:00:00+00:00 [queued]>
[2023-11-06T12:17:55.198+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-01T00:00:00+00:00 [queued]>
[2023-11-06T12:17:55.199+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-06T12:17:55.263+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): task_a> on 2023-10-01 00:00:00+00:00
[2023-11-06T12:17:55.328+0000] {standard_task_runner.py:57} INFO - Started process 1881 to run task
[2023-11-06T12:17:55.348+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'catchup_and_backfill_dag', 'task_a', 'scheduled__2023-10-01T00:00:00+00:00', '--job-id', '131', '--raw', '--subdir', 'DAGS_FOLDER/catchup_and_backfill_dag.py', '--cfg-path', '/tmp/tmpmq49m969']
[2023-11-06T12:17:55.367+0000] {standard_task_runner.py:85} INFO - Job 131: Subtask task_a
[2023-11-06T12:17:55.667+0000] {task_command.py:416} INFO - Running <TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-01T00:00:00+00:00 [running]> on host cf1baac588aa
[2023-11-06T12:17:56.242+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='safarnejad' AIRFLOW_CTX_DAG_ID='catchup_and_backfill_dag' AIRFLOW_CTX_TASK_ID='task_a' AIRFLOW_CTX_EXECUTION_DATE='2023-10-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-01T00:00:00+00:00'
[2023-11-06T12:17:56.254+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-06T12:17:56.265+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo Hello World :)']
[2023-11-06T12:17:56.288+0000] {subprocess.py:86} INFO - Output:
[2023-11-06T12:17:56.297+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: syntax error near unexpected token `)'
[2023-11-06T12:17:56.298+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: `echo Hello World :)'
[2023-11-06T12:17:56.301+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-11-06T12:17:56.349+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-11-06T12:17:56.376+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=catchup_and_backfill_dag, task_id=task_a, execution_date=20231001T000000, start_date=20231106T121755, end_date=20231106T121756
[2023-11-06T12:17:56.461+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 131 for task task_a (Bash command failed. The command returned a non-zero exit code 2.; 1881)
[2023-11-06T12:17:56.486+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-06T12:17:56.719+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-06T12:18:58.703+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-01T00:00:00+00:00 [queued]>
[2023-11-06T12:18:58.726+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-01T00:00:00+00:00 [queued]>
[2023-11-06T12:18:58.729+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-06T12:18:58.763+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): task_a> on 2023-10-01 00:00:00+00:00
[2023-11-06T12:18:58.794+0000] {standard_task_runner.py:57} INFO - Started process 1983 to run task
[2023-11-06T12:18:58.802+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'catchup_and_backfill_dag', 'task_a', 'scheduled__2023-10-01T00:00:00+00:00', '--job-id', '147', '--raw', '--subdir', 'DAGS_FOLDER/catchup_and_backfill_dag.py', '--cfg-path', '/tmp/tmpjaeq0yb6']
[2023-11-06T12:18:58.813+0000] {standard_task_runner.py:85} INFO - Job 147: Subtask task_a
[2023-11-06T12:18:58.927+0000] {task_command.py:416} INFO - Running <TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-01T00:00:00+00:00 [running]> on host cf1baac588aa
[2023-11-06T12:18:59.228+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='safarnejad' AIRFLOW_CTX_DAG_ID='catchup_and_backfill_dag' AIRFLOW_CTX_TASK_ID='task_a' AIRFLOW_CTX_EXECUTION_DATE='2023-10-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-01T00:00:00+00:00'
[2023-11-06T12:18:59.231+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-06T12:18:59.232+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo Hello World.']
[2023-11-06T12:18:59.249+0000] {subprocess.py:86} INFO - Output:
[2023-11-06T12:18:59.255+0000] {subprocess.py:93} INFO - Hello World.
[2023-11-06T12:18:59.256+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-11-06T12:18:59.317+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=catchup_and_backfill_dag, task_id=task_a, execution_date=20231001T000000, start_date=20231106T121858, end_date=20231106T121859
[2023-11-06T12:18:59.357+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-06T12:18:59.408+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
