[2023-11-05T11:30:11.816+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_first_dag.task_b manual__2023-11-05T11:28:08.932764+00:00 [queued]>
[2023-11-05T11:30:11.831+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_first_dag.task_b manual__2023-11-05T11:28:08.932764+00:00 [queued]>
[2023-11-05T11:30:11.832+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-11-05T11:30:11.857+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): task_b> on 2023-11-05 11:28:08.932764+00:00
[2023-11-05T11:30:11.862+0000] {standard_task_runner.py:57} INFO - Started process 3193 to run task
[2023-11-05T11:30:11.867+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'my_first_dag', 'task_b', 'manual__2023-11-05T11:28:08.932764+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpemb1ze44']
[2023-11-05T11:30:11.873+0000] {standard_task_runner.py:85} INFO - Job 30: Subtask task_b
[2023-11-05T11:30:11.945+0000] {task_command.py:416} INFO - Running <TaskInstance: my_first_dag.task_b manual__2023-11-05T11:28:08.932764+00:00 [running]> on host 6f8d85da5f7c
[2023-11-05T11:30:12.076+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='safarnejad' AIRFLOW_CTX_DAG_ID='my_first_dag' AIRFLOW_CTX_TASK_ID='task_b' AIRFLOW_CTX_EXECUTION_DATE='2023-11-05T11:28:08.932764+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-05T11:28:08.932764+00:00'
[2023-11-05T11:30:12.078+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-05T11:30:12.079+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cp /opt/***/dags/consolidat']
[2023-11-05T11:30:12.091+0000] {subprocess.py:86} INFO - Output:
[2023-11-05T11:30:12.096+0000] {subprocess.py:93} INFO - cp: missing destination file operand after '/opt/***/dags/consolidat'
[2023-11-05T11:30:12.097+0000] {subprocess.py:93} INFO - Try 'cp --help' for more information.
[2023-11-05T11:30:12.099+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-11-05T11:30:12.116+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-11-05T11:30:12.124+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=my_first_dag, task_id=task_b, execution_date=20231105T112808, start_date=20231105T113011, end_date=20231105T113012
[2023-11-05T11:30:12.145+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 30 for task task_b (Bash command failed. The command returned a non-zero exit code 1.; 3193)
[2023-11-05T11:30:12.162+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-05T11:30:12.198+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
