[2023-11-06T12:05:51.848+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-05T00:00:00+00:00 [queued]>
[2023-11-06T12:05:51.888+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-05T00:00:00+00:00 [queued]>
[2023-11-06T12:05:51.893+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-11-06T12:05:51.995+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): task_a> on 2023-10-05 00:00:00+00:00
[2023-11-06T12:05:52.008+0000] {standard_task_runner.py:57} INFO - Started process 793 to run task
[2023-11-06T12:05:52.072+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'catchup_and_backfill_dag', 'task_a', 'scheduled__2023-10-05T00:00:00+00:00', '--job-id', '79', '--raw', '--subdir', 'DAGS_FOLDER/catchup_and_backfill_dag.py', '--cfg-path', '/tmp/tmpzgc7vp2l']
[2023-11-06T12:05:52.088+0000] {standard_task_runner.py:85} INFO - Job 79: Subtask task_a
[2023-11-06T12:05:52.736+0000] {task_command.py:416} INFO - Running <TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-05T00:00:00+00:00 [running]> on host cf1baac588aa
[2023-11-06T12:05:53.507+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='safarnejad' AIRFLOW_CTX_DAG_ID='catchup_and_backfill_dag' AIRFLOW_CTX_TASK_ID='task_a' AIRFLOW_CTX_EXECUTION_DATE='2023-10-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-05T00:00:00+00:00'
[2023-11-06T12:05:53.520+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-06T12:05:53.521+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo Hello World :)']
[2023-11-06T12:05:53.571+0000] {subprocess.py:86} INFO - Output:
[2023-11-06T12:05:53.577+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: syntax error near unexpected token `)'
[2023-11-06T12:05:53.584+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: `echo Hello World :)'
[2023-11-06T12:05:53.585+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-11-06T12:05:53.638+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-11-06T12:05:53.658+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=catchup_and_backfill_dag, task_id=task_a, execution_date=20231005T000000, start_date=20231106T120551, end_date=20231106T120553
[2023-11-06T12:05:53.853+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 79 for task task_a (Bash command failed. The command returned a non-zero exit code 2.; 793)
[2023-11-06T12:05:53.915+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-06T12:05:53.999+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
