[2023-11-07T16:09:46.669+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_like_object_store_sensor_dag.task_a manual__2023-11-07T16:08:01.031913+00:00 [queued]>
[2023-11-07T16:09:46.685+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_like_object_store_sensor_dag.task_a manual__2023-11-07T16:08:01.031913+00:00 [queued]>
[2023-11-07T16:09:46.686+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 7
[2023-11-07T16:09:46.711+0000] {taskinstance.py:1382} INFO - Executing <Task(S3KeySensor): task_a> on 2023-11-07 16:08:01.031913+00:00
[2023-11-07T16:09:46.717+0000] {standard_task_runner.py:57} INFO - Started process 2099 to run task
[2023-11-07T16:09:46.722+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 's3_like_object_store_sensor_dag', 'task_a', 'manual__2023-11-07T16:08:01.031913+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/s3_like_object_store_sensor_dag.py', '--cfg-path', '/tmp/tmpl1_4ly4y']
[2023-11-07T16:09:46.726+0000] {standard_task_runner.py:85} INFO - Job 71: Subtask task_a
[2023-11-07T16:09:46.795+0000] {task_command.py:416} INFO - Running <TaskInstance: s3_like_object_store_sensor_dag.task_a manual__2023-11-07T16:08:01.031913+00:00 [running]> on host a4689ea3b4a1
[2023-11-07T16:09:46.904+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='safarnejad' AIRFLOW_CTX_DAG_ID='s3_like_object_store_sensor_dag' AIRFLOW_CTX_TASK_ID='task_a' AIRFLOW_CTX_EXECUTION_DATE='2023-11-07T16:08:01.031913+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-07T16:08:01.031913+00:00'
[2023-11-07T16:09:46.906+0000] {s3.py:106} INFO - Poking for key : s3://***/requirements.txt
[2023-11-07T16:09:46.918+0000] {base.py:73} INFO - Using connection ID 'minio-s3' for task execution.
[2023-11-07T16:09:46.919+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='minio-s3', conn_type='aws') credentials retrieved from login and password.
[2023-11-07T16:09:48.138+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 144, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 257, in execute
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 239, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 137, in poke
    return self._check_key(self.bucket_key)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 125, in _check_key
    obj = self.hook.head_object(key, bucket_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 135, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 89, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 884, in head_object
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 879, in head_object
    return self.get_conn().head_object(Bucket=bucket_name, Key=key)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
[2023-11-07T16:09:48.151+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=s3_like_object_store_sensor_dag, task_id=task_a, execution_date=20231107T160801, start_date=20231107T160946, end_date=20231107T160948
[2023-11-07T16:09:48.177+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 71 for task task_a (An error occurred (403) when calling the HeadObject operation: Forbidden; 2099)
[2023-11-07T16:09:48.227+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-07T16:09:48.255+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
