[2023-11-06T15:07:36.766+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_conn_dag.task_a manual__2023-11-06T15:07:35.613745+00:00 [queued]>
[2023-11-06T15:07:36.819+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_conn_dag.task_a manual__2023-11-06T15:07:35.613745+00:00 [queued]>
[2023-11-06T15:07:36.821+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-06T15:07:36.875+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): task_a> on 2023-11-06 15:07:35.613745+00:00
[2023-11-06T15:07:36.890+0000] {standard_task_runner.py:57} INFO - Started process 485 to run task
[2023-11-06T15:07:36.910+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'postgres_conn_dag', 'task_a', 'manual__2023-11-06T15:07:35.613745+00:00', '--job-id', '350', '--raw', '--subdir', 'DAGS_FOLDER/***_connection_dag.py', '--cfg-path', '/tmp/tmpumojibom']
[2023-11-06T15:07:36.936+0000] {standard_task_runner.py:85} INFO - Job 350: Subtask task_a
[2023-11-06T15:07:37.081+0000] {task_command.py:416} INFO - Running <TaskInstance: postgres_conn_dag.task_a manual__2023-11-06T15:07:35.613745+00:00 [running]> on host cf1baac588aa
[2023-11-06T15:07:37.225+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='safarnejad' AIRFLOW_CTX_DAG_ID='postgres_conn_dag' AIRFLOW_CTX_TASK_ID='task_a' AIRFLOW_CTX_EXECUTION_DATE='2023-11-06T15:07:35.613745+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-06T15:07:35.613745+00:00'
[2023-11-06T15:07:37.226+0000] {sql.py:274} INFO - Executing: 
            create table  if not exists dag_runs(
                dt date,
                dag_id character varying,
                primary key (dt, dag_id)
            )
        
[2023-11-06T15:07:37.244+0000] {base.py:73} INFO - Using connection ID 'postgres-test' for task execution.
[2023-11-06T15:07:37.267+0000] {base.py:73} INFO - Using connection ID 'postgres-test' for task execution.
[2023-11-06T15:07:45.274+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 155, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "host.docker.local" to address: Temporary failure in name resolution

[2023-11-06T15:07:45.294+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=postgres_conn_dag, task_id=task_a, execution_date=20231106T150735, start_date=20231106T150736, end_date=20231106T150745
[2023-11-06T15:07:45.315+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 350 for task task_a (could not translate host name "host.docker.local" to address: Temporary failure in name resolution
; 485)
[2023-11-06T15:07:45.353+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-06T15:07:45.374+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
