[2023-11-06T12:03:50.133+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-06T00:00:00+00:00 [queued]>
[2023-11-06T12:03:50.164+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-06T00:00:00+00:00 [queued]>
[2023-11-06T12:03:50.165+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-06T12:03:50.224+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): task_a> on 2023-10-06 00:00:00+00:00
[2023-11-06T12:03:50.233+0000] {standard_task_runner.py:57} INFO - Started process 643 to run task
[2023-11-06T12:03:50.243+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'catchup_and_backfill_dag', 'task_a', 'scheduled__2023-10-06T00:00:00+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/catchup_and_backfill_dag.py', '--cfg-path', '/tmp/tmp2t3rjnmh']
[2023-11-06T12:03:50.251+0000] {standard_task_runner.py:85} INFO - Job 64: Subtask task_a
[2023-11-06T12:03:50.421+0000] {task_command.py:416} INFO - Running <TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-06T00:00:00+00:00 [running]> on host cf1baac588aa
[2023-11-06T12:03:50.599+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='safarnejad' AIRFLOW_CTX_DAG_ID='catchup_and_backfill_dag' AIRFLOW_CTX_TASK_ID='task_a' AIRFLOW_CTX_EXECUTION_DATE='2023-10-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-06T00:00:00+00:00'
[2023-11-06T12:03:50.601+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-06T12:03:50.603+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo Hello World :)']
[2023-11-06T12:03:50.618+0000] {subprocess.py:86} INFO - Output:
[2023-11-06T12:03:50.622+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: syntax error near unexpected token `)'
[2023-11-06T12:03:50.623+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: `echo Hello World :)'
[2023-11-06T12:03:50.624+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-11-06T12:03:50.649+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-11-06T12:03:50.659+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=catchup_and_backfill_dag, task_id=task_a, execution_date=20231006T000000, start_date=20231106T120350, end_date=20231106T120350
[2023-11-06T12:03:50.802+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 64 for task task_a (Bash command failed. The command returned a non-zero exit code 2.; 643)
[2023-11-06T12:03:50.835+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-06T12:03:50.876+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-06T12:17:56.818+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-06T00:00:00+00:00 [queued]>
[2023-11-06T12:17:56.852+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-06T00:00:00+00:00 [queued]>
[2023-11-06T12:17:56.854+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-06T12:17:56.978+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): task_a> on 2023-10-06 00:00:00+00:00
[2023-11-06T12:17:57.015+0000] {standard_task_runner.py:57} INFO - Started process 1893 to run task
[2023-11-06T12:17:57.030+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'catchup_and_backfill_dag', 'task_a', 'scheduled__2023-10-06T00:00:00+00:00', '--job-id', '136', '--raw', '--subdir', 'DAGS_FOLDER/catchup_and_backfill_dag.py', '--cfg-path', '/tmp/tmpvmty0ya0']
[2023-11-06T12:17:57.042+0000] {standard_task_runner.py:85} INFO - Job 136: Subtask task_a
[2023-11-06T12:17:57.349+0000] {task_command.py:416} INFO - Running <TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-06T00:00:00+00:00 [running]> on host cf1baac588aa
[2023-11-06T12:17:57.632+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='safarnejad' AIRFLOW_CTX_DAG_ID='catchup_and_backfill_dag' AIRFLOW_CTX_TASK_ID='task_a' AIRFLOW_CTX_EXECUTION_DATE='2023-10-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-06T00:00:00+00:00'
[2023-11-06T12:17:57.638+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-06T12:17:57.641+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo Hello World :)']
[2023-11-06T12:17:57.665+0000] {subprocess.py:86} INFO - Output:
[2023-11-06T12:17:57.669+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: syntax error near unexpected token `)'
[2023-11-06T12:17:57.670+0000] {subprocess.py:93} INFO - /bin/bash: -c: line 1: `echo Hello World :)'
[2023-11-06T12:17:57.671+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-11-06T12:17:57.698+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-11-06T12:17:57.709+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=catchup_and_backfill_dag, task_id=task_a, execution_date=20231006T000000, start_date=20231106T121756, end_date=20231106T121757
[2023-11-06T12:17:57.820+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 136 for task task_a (Bash command failed. The command returned a non-zero exit code 2.; 1893)
[2023-11-06T12:17:57.850+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-06T12:17:57.894+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-06T12:18:59.542+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-06T00:00:00+00:00 [queued]>
[2023-11-06T12:18:59.565+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-06T00:00:00+00:00 [queued]>
[2023-11-06T12:18:59.566+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-06T12:18:59.717+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): task_a> on 2023-10-06 00:00:00+00:00
[2023-11-06T12:18:59.733+0000] {standard_task_runner.py:57} INFO - Started process 1996 to run task
[2023-11-06T12:18:59.740+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'catchup_and_backfill_dag', 'task_a', 'scheduled__2023-10-06T00:00:00+00:00', '--job-id', '152', '--raw', '--subdir', 'DAGS_FOLDER/catchup_and_backfill_dag.py', '--cfg-path', '/tmp/tmp8wbglhur']
[2023-11-06T12:18:59.753+0000] {standard_task_runner.py:85} INFO - Job 152: Subtask task_a
[2023-11-06T12:18:59.879+0000] {task_command.py:416} INFO - Running <TaskInstance: catchup_and_backfill_dag.task_a scheduled__2023-10-06T00:00:00+00:00 [running]> on host cf1baac588aa
[2023-11-06T12:19:00.081+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='safarnejad' AIRFLOW_CTX_DAG_ID='catchup_and_backfill_dag' AIRFLOW_CTX_TASK_ID='task_a' AIRFLOW_CTX_EXECUTION_DATE='2023-10-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-06T00:00:00+00:00'
[2023-11-06T12:19:00.083+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-06T12:19:00.085+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo Hello World.']
[2023-11-06T12:19:00.103+0000] {subprocess.py:86} INFO - Output:
[2023-11-06T12:19:00.106+0000] {subprocess.py:93} INFO - Hello World.
[2023-11-06T12:19:00.107+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-11-06T12:19:00.160+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=catchup_and_backfill_dag, task_id=task_a, execution_date=20231006T000000, start_date=20231106T121859, end_date=20231106T121900
[2023-11-06T12:19:00.208+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-06T12:19:00.270+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
