[2023-11-08T15:18:15.494+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sql_hook_to_s3.load_data_from_pg_to_s3 manual__2023-11-08T14:52:35.114580+00:00 [queued]>
[2023-11-08T15:18:15.509+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sql_hook_to_s3.load_data_from_pg_to_s3 manual__2023-11-08T14:52:35.114580+00:00 [queued]>
[2023-11-08T15:18:15.510+0000] {taskinstance.py:1361} INFO - Starting attempt 5 of 10
[2023-11-08T15:18:15.532+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_data_from_pg_to_s3> on 2023-11-08 14:52:35.114580+00:00
[2023-11-08T15:18:15.539+0000] {standard_task_runner.py:57} INFO - Started process 5262 to run task
[2023-11-08T15:18:15.544+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'sql_hook_to_s3', 'load_data_from_pg_to_s3', 'manual__2023-11-08T14:52:35.114580+00:00', '--job-id', '211', '--raw', '--subdir', 'DAGS_FOLDER/sql_hook_to_s3_dag.py', '--cfg-path', '/tmp/tmp2s6vbuhc']
[2023-11-08T15:18:15.548+0000] {standard_task_runner.py:85} INFO - Job 211: Subtask load_data_from_pg_to_s3
[2023-11-08T15:18:15.617+0000] {task_command.py:416} INFO - Running <TaskInstance: sql_hook_to_s3.load_data_from_pg_to_s3 manual__2023-11-08T14:52:35.114580+00:00 [running]> on host 5cb9101badf1
[2023-11-08T15:18:15.747+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='safarnejad.ho@gmail.com' AIRFLOW_CTX_DAG_OWNER='safarnejad' AIRFLOW_CTX_DAG_ID='sql_hook_to_s3' AIRFLOW_CTX_TASK_ID='load_data_from_pg_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2023-11-08T14:52:35.114580+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-08T14:52:35.114580+00:00'
[2023-11-08T15:18:15.758+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:206 AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
[2023-11-08T15:18:15.771+0000] {base.py:73} INFO - Using connection ID 'orders-pg-conn' for task execution.
[2023-11-08T15:18:15.788+0000] {sql_hook_to_s3_dag.py:40} INFO - Saved orders to orders_20231108.txt file.
[2023-11-08T15:18:15.800+0000] {base.py:73} INFO - Using connection ID 'minio-s3' for task execution.
[2023-11-08T15:18:15.801+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='minio-s3', conn_type='aws') credentials retrieved from login and password.
[2023-11-08T15:18:15.803+0000] {logging_mixin.py:154} WARNING - <string>:9 AirflowProviderDeprecationWarning: extra['host'] is deprecated and will be removed in a future release. Please set extra['endpoint_url'] instead
[2023-11-08T15:18:16.509+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/sql_hook_to_s3_dag.py", line 43, in load_data_to_file
    s3_hook.load_file(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 135, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 89, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 1082, in load_file
    client.upload_file(filename, bucket_name, key, ExtraArgs=extra_args, Config=self.transfer_config)
  File "/home/airflow/.local/lib/python3.8/site-packages/boto3/s3/inject.py", line 143, in upload_file
    return transfer.upload_file(
  File "/home/airflow/.local/lib/python3.8/site-packages/boto3/s3/transfer.py", line 292, in upload_file
    future.result()
  File "/home/airflow/.local/lib/python3.8/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
  File "/home/airflow/.local/lib/python3.8/site-packages/s3transfer/futures.py", line 266, in result
    raise self._exception
  File "/home/airflow/.local/lib/python3.8/site-packages/s3transfer/tasks.py", line 269, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/s3transfer/upload.py", line 591, in _submit
    upload_input_manager.provide_transfer_size(transfer_future)
  File "/home/airflow/.local/lib/python3.8/site-packages/s3transfer/upload.py", line 244, in provide_transfer_size
    self._osutil.get_file_size(transfer_future.meta.call_args.fileobj)
  File "/home/airflow/.local/lib/python3.8/site-packages/s3transfer/utils.py", line 247, in get_file_size
    return os.path.getsize(filename)
  File "/usr/local/lib/python3.8/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: 'dags/orders_20231108.txt'
[2023-11-08T15:18:16.532+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=sql_hook_to_s3, task_id=load_data_from_pg_to_s3, execution_date=20231108T145235, start_date=20231108T151815, end_date=20231108T151816
[2023-11-08T15:18:16.550+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 211 for task load_data_from_pg_to_s3 ([Errno 2] No such file or directory: 'dags/orders_20231108.txt'; 5262)
[2023-11-08T15:18:16.565+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-08T15:18:16.590+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
